#!/bin/bash
# Simple script to update Ubuntu/Debian and Arch Linux
if [ "$(lsb_release -is)" == ["Ubuntu"] || ["Debian"] ]; then
  sudo apt update | tee ; sudo apt upgrade -yy | tee
  else
    echo "no debian distro found"
fi
